# Generated by Django 6.0.3 on 2026-04-12 11:52

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("publish_date", models.DateField(verbose_name="Publish Date")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("germany", "deutschland verstehen"),
                            ("german-learning", "deutsch lernen"),
                            ("coding", "coding journey"),
                        ],
                        default="coding",
                        max_length=50,
                        verbose_name="Category",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("rich_text", 0), ("raw_html", 1)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "link",
                                        "code",
                                        "image",
                                        "hr",
                                        "blockquote",
                                    ],
                                    "label": "Rich Text",
                                },
                            ),
                            1: (
                                "wagtail.blocks.RawHTMLBlock",
                                (),
                                {"label": "Raw HTML"},
                            ),
                        },
                        verbose_name="Body",
                    ),
                ),
                (
                    "featured_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Featured Image",
                    ),
                ),
            ],
            options={"verbose_name": "Blog Post", "verbose_name_plural": "Blog Posts",},
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                ("caption", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="posts.post",
                    ),
                ),
            ],
        ),
    ]
