# Generated by Django 6.0.3 on 2026-04-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_post_title"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="created_at",),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="post", name="title", field=models.CharField(max_length=200),
        ),
    ]
