# Generated by Django 6.0.3 on 2026-06-02 08:33

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_delete_postimage"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name": "blog post", "verbose_name_plural": "blog posts"},
        ),
        migrations.RemoveField(model_name="post", name="publish_date",),
        migrations.AddField(
            model_name="post",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="发布日期"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 0),
                    ("markdown", 1),
                    ("image", 2),
                    ("embed", 3),
                    ("table", 4),
                    ("quote", 5),
                    ("raw_html", 6),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"icon": "doc-full", "label": "富文本"},
                    ),
                    1: (
                        "wagtailmarkdown.blocks.MarkdownBlock",
                        (),
                        {"icon": "code", "label": "Markdown"},
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"icon": "image", "label": "图片"},
                    ),
                    3: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"icon": "media", "label": "嵌入视频/内容"},
                    ),
                    4: (
                        "wagtail.contrib.table_block.blocks.TableBlock",
                        (),
                        {"icon": "table", "label": "表格"},
                    ),
                    5: (
                        "wagtail.blocks.BlockQuoteBlock",
                        (),
                        {"icon": "openquote", "label": "引用"},
                    ),
                    6: (
                        "wagtail.blocks.RawHTMLBlock",
                        (),
                        {"icon": "code", "label": "Raw HTML"},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("germany", "Deutschland verstehen"),
                    ("german-learning", "Deutsch lernen"),
                    ("coding", "Coding Journey"),
                ],
                default="german-learning",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="featured_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
