# Generated by Django 6.0.3 on 2026-06-02 09:09

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_post_options_remove_post_publish_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 0),
                    ("markdown", 1),
                    ("code", 4),
                    ("image", 5),
                    ("embed", 6),
                    ("table", 7),
                    ("quote", 8),
                    ("raw_html", 9),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"icon": "doc-full", "label": "Rich text"},
                    ),
                    1: (
                        "wagtailmarkdown.blocks.MarkdownBlock",
                        (),
                        {"icon": "code", "label": "Markdown"},
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bash", "Bash/Shell"),
                                ("css", "CSS"),
                                ("diff", "diff"),
                                ("html", "HTML"),
                                ("javascript", "Javascript"),
                                ("json", "JSON"),
                                ("python", "Python"),
                                ("scss", "SCSS"),
                                ("yaml", "YAML"),
                            ],
                            "help_text": "Coding language",
                            "identifier": "language",
                            "label": "Language",
                        },
                    ),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"identifier": "code", "label": "Code"},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("language", 2), ("code", 3)]],
                        {"icon": "code", "label": "code"},
                    ),
                    5: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"icon": "image", "label": "image"},
                    ),
                    6: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"icon": "media", "label": "media"},
                    ),
                    7: (
                        "wagtail.contrib.table_block.blocks.TableBlock",
                        (),
                        {"icon": "table", "label": "table"},
                    ),
                    8: (
                        "wagtail.blocks.BlockQuoteBlock",
                        (),
                        {"icon": "openquote", "label": "quote"},
                    ),
                    9: (
                        "wagtail.blocks.RawHTMLBlock",
                        (),
                        {"icon": "code", "label": "Raw HTML"},
                    ),
                },
            ),
        ),
    ]
