# Generated by Django 6.0.3 on 2026-04-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_remove_post_created_at_post_image_alter_post_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("germany", "德国了解"),
                    ("german-learning", "德语学习"),
                    ("coding", "编程学习"),
                ],
                default="coding",
                max_length=50,
            ),
        ),
    ]
