# Generated by Django 6.0.3 on 2026-04-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("germany", "Deutschland verstehen"),
                    ("german-learning", "Deutsch lernen"),
                    ("coding", "Coding Journey"),
                ],
                default="coding",
                max_length=50,
            ),
        ),
    ]
