# Generated by Django 6.0.3 on 2026-06-09 07:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_alter_post_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 0),
                    ("markdown", 1),
                    ("image", 2),
                    ("embed", 3),
                    ("table", 4),
                    ("quote", 5),
                    ("raw_html", 6),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"icon": "doc-full", "label": "Rich text"},
                    ),
                    1: (
                        "wagtailmarkdown.blocks.MarkdownBlock",
                        (),
                        {"icon": "code", "label": "Markdown"},
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"icon": "image", "label": "image"},
                    ),
                    3: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"icon": "media", "label": "media"},
                    ),
                    4: (
                        "wagtail.contrib.table_block.blocks.TableBlock",
                        (),
                        {"icon": "table", "label": "table"},
                    ),
                    5: (
                        "wagtail.blocks.BlockQuoteBlock",
                        (),
                        {"icon": "openquote", "label": "quote"},
                    ),
                    6: (
                        "wagtail.blocks.RawHTMLBlock",
                        (),
                        {"icon": "code", "label": "Raw HTML"},
                    ),
                },
            ),
        ),
    ]
