# Generated by Django 6.0.3 on 2026-06-09 12:33

import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_alter_post_body"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name": "Blog Post", "verbose_name_plural": "Blog Posts"},
        ),
        migrations.RemoveField(model_name="post", name="date",),
        migrations.AddField(
            model_name="post",
            name="publish_date",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="publish date"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 0),
                    ("markdown", 1),
                    ("image", 2),
                    ("embed", 3),
                    ("table", 4),
                    ("raw_html", 5),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"icon": "doc-full", "label": "Rich text"},
                    ),
                    1: (
                        "wagtailmarkdown.blocks.MarkdownBlock",
                        (),
                        {"icon": "code", "label": "Markdown"},
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"icon": "image", "label": "Image"},
                    ),
                    3: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"icon": "media", "label": "Embed media"},
                    ),
                    4: (
                        "wagtail.contrib.table_block.blocks.TableBlock",
                        (),
                        {"icon": "table", "label": "Table"},
                    ),
                    5: (
                        "wagtail.blocks.RawHTMLBlock",
                        (),
                        {"icon": "code", "label": "Raw HTML"},
                    ),
                },
            ),
        ),
    ]
